version: '2'

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime
            - ./data:/data/db
        ports:
            - 27017:27017/tcp
        environment:
            - MONGO_INITDB_DATABASE=main
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root123

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root123
